require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'
require_relative '../node_modules/react-native-permissions/scripts/setup'

platform :ios, '12.4'
install! 'cocoapods', :deterministic_uuids => false

setup_permissions([
  'Camera',
  'Microphone',
  'Notifications',
])

production = ENV["PRODUCTION"] == "1"

target 'Portal4Edu_V2' do

  config = use_native_modules!

  # Flags change depending on the env values.
  flags = get_default_flags()

  

  use_react_native!(
    :path => config[:reactNativePath],
    # to enable hermes on iOS, change `false` to `true` and then install pods
    :production => production,
    :hermes_enabled => flags[:hermes_enabled],
    :fabric_enabled => flags[:fabric_enabled],
    :flipper_configuration => FlipperConfiguration.enabled,
    # An absolute path to your application root.
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )

  target 'Portal4Edu_V2Tests' do
    inherit! :complete
    # Pods for testing
  end

  #post_install do |installer|
   # react_native_post_install(installer)
    #__apply_Xcode_12_5_M1_post_install_workaround(installer)
  #end

  post_install do |installer|
    react_native_post_install(installer)
    __apply_Xcode_12_5_M1_post_install_workaround(installer)
    installer.pods_project.targets.each do |target|
     target.build_configurations.each do |config|
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '12.0'
      config.build_settings['ARCHS[sdk=iphonesimulator*]'] = 'x86_64'
      config.build_settings['GCC_PREPROCESSOR_DEFINITIONS'] ||= ['$(inherited)', '_LIBCPP_ENABLE_CXX17_REMOVED_UNARY_BINARY_FUNCTION']
     end
    end
  end

end

target 'OneSignalNotificationServiceExtension' do
  #pod 'OneSignalXCFramework', '= 5.1.5'
  pod 'OneSignalXCFramework', '>= 3.0', '< 4.0'
end